language: ruby
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- bundle exec rake db:create db:migrate RAILS_ENV=test
cache:
  bundler: true
  directories:
  - node_modules
  yarn: true
install:
- bundle install
- nvm install node
- npm i -g yarn
- yarn
deploy:
  provider: heroku
  api_key:
    secure: OsJV7zLtU4tgScLoHW0oxRWEurvBu7jKXOuyzjlfrpuITydWYHFlh30vNXnnH0kiWidjzSDsWwfZMAPNQIX615KOq15pAuYe7pR6zfib5JzldUyFcDotb7q8diTqb8R3kANLJB1dJXCeBPL8pMmdYLwGOlbPgmHjdoH+QxT73BOMHSAY0jMYW32huHKQCaqb/arPkD4jPKjm4j2xf/1P0gwoh0pDo6+5qrX9AWXM3RnEWo1UAcgs1vE34gsoB5SdADw2GbcOylEUtv8ppidh0ncMXNBQ/z5WlJkofFuJ3vsXP4NeW1ncuTSEUpxZSGKrlm3lqq7zi2RPDGnSLzANDd5AGnR1WsltLtvr9nXB1OBfJZARjb9J+aNhszFK5GjVdjkaBhtLExy4lnrgdOOTaz1C+60kmQ0Ry9G1CA/3FQINuRmK57MHNE2q+Eo52Zx9MVNq62Cr1zmZ4AinuDucVam/7o4WAaWse1n2Iptf6K9VHCPLsCaPw66kwjofevTvtVbQH86/me73utP/XNS0TGQ5WvdISkgqjSMQ7+JWLFz/6KdfejbKhE3dm6bN7pScvGfE+7p9xuutgBpgzWdU2Ogx40zky/gjb9+em85qzxuL6BwDgNJf7TaEPjL+Ev7XiUECJXx7Q/5OuezlX9ICLPLgxoqVrpwqsUwqwFwRibk=
  app: proyecto-rails-restaurante
  on:
    repo: damonmoya/proyecto-rails-restaurante
