development:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'
  recaptcha_site_key: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
  recaptcha_secret_key: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'

production:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'
  recaptcha_site_key: '6Ldkk74aAAAAAKWy5AqN7qfLi-nKl3xz8S0tS09q'
  recaptcha_secret_key: '6Ldkk74aAAAAALT7a7q1Kp1XAw4-jfWnAIVWcTcT'

test:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'
  recaptcha_site_key: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
  recaptcha_secret_key: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'