development:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'

production:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'

test:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'