development:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'
  recaptcha_site_key: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
  recaptcha_secret_key: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'

production:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'
  recaptcha_site_key: '6Lexzr4aAAAAAB5whsOE6UpoOZ20KUUDmlI-5bvW'
  recaptcha_secret_key: '6Lexzr4aAAAAAIlKrq7GbWzZOhAlVkZ_ifTSEFhu'

test:
  stripe_secret_key: 'sk_test_51IiyYkEDqZ0GL2iFtTyZdYv35aVQmatNX7dBSHny6sGQdnGmhD1I2ngFBPiDmopf200Gknm1d5OIrU1nMIgEs28400x70FO83R'
  stripe_publishable_key: 'pk_test_51IiyYkEDqZ0GL2iF1RR05lQxOvnGwIVE2oGrDE64ylKQaWyzXm6bdCkGoEp2v03AnxF6GN5b9q2yAzVyZHJIR4rX00HurZdGki'
  recaptcha_site_key: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
  recaptcha_secret_key: '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe'